### ISSUE TITLE
Error when generating sitemap on Strapi 4.14.4 and Node v18

### ISSUE THREAD

**Issue by squelix** [boazpoolman/strapi-plugin-sitemap#140]
### Describe the bug

I was in Strapi 4.14.3 and sitemap plugin 2.0.11 and since I updated Strapi and the sitemap plugin to 4.14.4 and 3.0.3 the sitemap is not generating.

### Steps to reproduce the behavior

1. Go to sitemap settings
2. Click on Generate Sitemap
3. ERROR

```shell
[2023-10-12 15:47:27.860] error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. TypeError: sitemapEntries.reduce is not a function

  Error
      at Object.createSitemap (/Users/mickael/Workspace/cms-v3/dist/src/extensions/sitemap/strapi-server.js:37:27)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.buildSitemap (/Users/mickael/Workspace/cms-v3/node_modules/strapi-plugin-sitemap/server/controllers/core.js:14:13)
      at async returnBodyMiddleware (/Users/mickael/Workspace/cms-v3/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:45:20)
      at async policiesMiddleware (/Users/mickael/Workspace/cms-v3/node_modules/@strapi/strapi/dist/services/server/policy.js:16:9)
      at async /Users/mickael/Workspace/cms-v3/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:29:16
      at async serve (/Users/mickael/Workspace/cms-v3/node_modules/koa-static/index.js:59:5)
      at async returnBodyMiddleware (/Users/mickael/Workspace/cms-v3/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:45:20)
      at async policiesMiddleware (/Users/mickael/Workspace/cms-v3/node_modules/@strapi/strapi/dist/services/server/policy.js:16:9)
      at async /Users/mickael/Workspace/cms-v3/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:29:16

```

### Expected behavior

The sitemap should be generated. 

### System

- Node.js version: v18
- NPM version: 9.8.1
- Strapi version: 4.14.4
- Plugin version: 3.0.3
- Database: Postgres
- Operating system: Docker or MacOS

**Comment by boazpoolman** [comment]
Hi @squelix

I've tried to reproduce this issue but I couldn't.
I was testing with Strapi 4.14.3 and sitemap plugin 2.0.11 and then I updated Strapi and the sitemap plugin to 4.14.4 and 3.0.3. Though the generation of the sitemap was succesful.

Looking at your backtrace it looks like you've extended the sitemap plugin in the `src/extensions` folder:
```
/cms-v3/dist/src/extensions/sitemap/strapi-server.js
```
It is likely that the extension you wrote is not compatible anymore with the latest version of the plugin.

Could you delete/rewrite that extension and try again?

**Comment by boazpoolman** [comment]
I'm gonna close this due to inactivity.

@squelix If you still have any issues with the plugin feel free to open a new issue.
